<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ppscout_description</name>
  <version>0.1.0</version>
  <description>Robot description for the Scout Mini + Piper arm (URDF/xacro, models, RViz config)</description>
  <maintainer email="thalesasoares02@hotmail.com">thales</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>xacro</exec_depend>
  <exec_depend>scout_description</exec_depend>
  <exec_depend>agx_arm_description</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
